version: "3.8"
services:
  coursework: 
    container_name: coursework-backend
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
    env_file:
      - .env
    command: npm run dev
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data1:/data/db
      - config1:/data/configdb
volumes:
  data1:
  config1: