version: "3.8"
services:
  coursework: 
    container_name: coursework-backend
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
    env_file:
      - .env
    command: npm run dev
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db